
// # EllipticalOrbit
// # {
// #	Period            0.6152
// #	SemiMajorAxis     0.7233
// #	Eccentricity      0.0068
// #	Inclination       3.3947
// #	AscendingNode     76.681
// #	LongOfPericenter 131.533
// #    MeanLongitude    181.979
// # }

// Celestial body constructor
var CelestialBody = function(obj) {
	// Meta
	this.name = "";
	// Object shape info
	this.spherical = true; this.oblateness = 1.; this.radius = 1.;
	// TODO: Model info, to be implemented
    // Orbit parameters
    // 周期、半长轴、离心率、倾角、升交点黄经、平近点角 (历时原点假设轨道是圆形时的黄经偏移)
    this.orbit = {
        period: 1., semiMajorAxis: 1., eccentricity: 0.,
        inclination: 3.3947, ascendingNode: 0., meanLongitude: 0.
    };
    // Rotation parameters
    this.rotation = {
        
    };
};

var celestialBodies = [{
	searchterm:'Sun',
	revRadius:0,
	selftime: 0.1,
	time: 0,
	radius:1.5 * 50,
	ecc:0.0,
	incl:0.0,
	tilt:0,
	src:"res/sol/diffuse.png",
	ring:null,
	cloud:"res/grenn.jpg",
	usecloud: false,
	bump:"res/green.jpg",
	usebump:false,
	satlites:[]
}, {
	searchterm:'Mercury',
	revRadius:6 * 180,
	selftime: 58.65,
	time:0.24,
	radius:0.03825 * 100,
	ecc:0.206,
	incl:3.38,
	tilt:0.0352,
	stilt: 7,
	src:"res/mercurymap.jpg",
	ring:null,
    cloud:"res/grenn.jpg",
    usecloud: false,
	bump:"res/mercurybump_NRM.png",
	usebump:true,
	satlites:[]
},{
	searchterm:'Venus',
	revRadius:12 * 120,
	selftime:243,
	time:0.62,
	radius:0.09488 * 100,
	ecc:0.007,
	incl:3.86,
	tilt:177.4,
    stilt:3.4,
	src:"res/venusmap.jpg",
	ring:null,
    cloud:"res/grenn.jpg",
    usecloud: false,
	bump:"res/venusbump_NRM.png",
	usebump:true,
	satlites:[]
},{
	searchterm:'Earth',
	revRadius:18 * 100,
	selftime:1.0,
	time:1.0,
	radius:0.1 * 100,
	ecc:0.017,
	incl:7.25,
	tilt:23.44,
    stilt: 0,
	src:"res/earthmap1k.jpg",
	ring:null,
    cloud:"res/fair_cloud.png",
    usecloud: true,
	bump:"res/earthbump1k_NRM.png",
	usebump:true,
	satlites:[{
		searchterm:'Moon',
		revRadius:1 * 170,
		time:0.08,
		radius:0.04 * 100,
		ecc:0.0554,
		incl:0.0012,
		tilt: 0,
		stilt: 0,
		src:"res/moonmap1k.jpg",
		ring:null,
		bump:"res/moonbump1k_NRM.png",
		usebump:true
	}]
}, {
	searchterm:'Mars',
	revRadius:30 * 80,
	selftime:1.05,
	time:1.88,
	radius:0.053226 * 100,
	ecc:0.093,
	incl:5.65,
	tilt:25.19,
    stilt: 1.9,
	src:"res/mars_1k_color.jpg",
	ring:null,
    cloud:"res/grenn.jpg",
    usecloud: false,
	bump:"res/marsbump1k_NRM.png",
	usebump:true,
	satlites:[{
		searchterm:'Phobos',
		revRadius:1 * 100,
		time:0.08,
		radius:0.004*2 * 300,
		ecc:0.015,
		incl:1.093,
        tilt: 0,
        stilt: 5,
		src:"res/phobos.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	},{
		searchterm:'Deimos',
		revRadius:2 * 100,
		time:0.16,
		radius:0.002*2 * 4000,
		ecc:0.0,
		incl:0.93,
        tilt: 0,
        stilt: 0,
		src:"res/deimos.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	}]
}, {
	searchterm:'Jupiter',
	revRadius:96 * 35,
	selftime:0.42,
	time:11.86,
	radius:1.1209 * 30,
	ecc:0.048,
	incl:6.09,
	tilt:3.13,
    stilt:1.3,
	src:"res/jupitermap.jpg",
	ring:null,
    cloud:"res/grenn.jpg",
    usecloud: false,
	bump:"res/green.jpg",
	usebump:false,
	satlites:[{
		searchterm:'Ganymede',
		revRadius:10 * 50,
		time:0.02*4,
		radius:0.023*4 * 100,
		ecc:0.0013,
		incl:0.20,
        tilt: 0,
        stilt: 2,
		src:"res/ganymede.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	}, {
		searchterm:'Callisto',
		revRadius:18.9 * 40,
		time:0.04*4,
		radius:0.02*4 * 100,
		ecc:0.007,
		incl:0.192,
        tilt: 0,
        stilt: 5,
		src:"res/callisto.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	},{
		searchterm:'Io',
		revRadius:4.23 * -100,
		time:0.003*4,
		radius:0.015*4 * 100,
		ecc:0.004,
		incl:0.05,
        tilt: 0,
        stilt: 15,
		src:"res/io.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	},{
		searchterm:'Europa',
		revRadius:6.77 * -85,
		time:0.01*4,
		radius:0.012*4 * 100,
		ecc:0.009,
		incl:0.470,
        tilt: 0,
        stilt: 20,
		src:"res/europa.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	}]
},{
	searchterm:'Saturn',
	revRadius:240 * 20,
	selftime:0.42,
	time:29.46,
	radius:0.9449 * 30,
	ecc:0.054,
	incl:5.51,
	tilt:26.73,
    stilt: 2.5,
	src:"res/saturnmap.jpg",
	ring:"res/saturnring.jpg",
	ringalpha:"res/saturnringpattern.gif",
    cloud:"res/grenn.jpg",
    usecloud: false,
	bump:"res/green.jpg",
	usebump:false,
	satlites:[{
		searchterm:'Titan',
		revRadius:12.57 * 45,
		time:0.02*4,
		radius:0.02*4 * 100,
		ecc:0.0288,
		incl:0.348,
        tilt: 0,
        stilt: -5,
		src:"res/titan.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	},{
		searchterm:'Rhea',
		revRadius:5.2 * 110,
		time:0.01*4,
		radius:0.012*4 * 100,
		ecc:0.001,
		incl:0.345,
        tilt: 0,
        stilt: 15,
		src:"res/rhea.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	},{
		searchterm:'Iapetus',
		revRadius:35.6 * -16,
		time:0.2*4,
		radius:0.011*4 * 100,
		ecc:0.028,
		incl:15.47,
        tilt: 0,
        stilt: 25,
		src:"res/iapetus.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	},{
		searchterm:'Dione',
		revRadius:3.77 * -120,
		time:0.006*4,
		radius:0.004*4 * 100,
		ecc:0.002,
		incl:0.019,
        tilt: 0,
        stilt: 50,
		src:"res/dione.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	},{
		searchterm:'Tethys',
		revRadius:2.95 * 150,
		time:0.004*4,
		radius:0.009*4 * 100,
		ecc:0.0,
		incl:1.12,
        tilt: 0,
        stilt: 45,
		src:"res/tethys.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	}]
},{
	searchterm:'Uranus',
	revRadius:360 * 16,
	selftime:0.71,
	time:84.41,
	radius:0.4007 * 30,
	ecc:0.047,
	incl:6.48,
	tilt:97.77,
    stilt: 0.8,
	src:"res/uranusmap.jpg",
	ring:"res/uranusring.gif",
	ringalpha:"res/uranusringtrans.jpg",
    cloud:"res/grenn.jpg",
    usecloud: false,
	bump:"res/green.jpg",
	usebump:false,
	satlites:[{
		searchterm:'Titania',
		revRadius:4.36 * 50,
		time:0.025*4,
		radius:0.007*4 * 100,
		ecc:0.0011,
		incl:0.340,
        tilt: 0,
        stilt: 10,
		src:"res/titania.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	},{
		searchterm:'Oberon',
		revRadius:5.83 * 60,
		time:0.038*4,
		radius:0.006*4 * 100,
		ecc:0.0014,
		incl:0.058,
        tilt: 0,
        stilt: 45,
		src:"res/oberon.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	},{
		searchterm:'Umbriel',
		revRadius:2.66 * -65,
		time:0.01*4,
		radius:0.005*4 * 100,
		ecc:0.0039,
		incl:0.128,
        tilt: 0,
        stilt: 30,
		src:"res/umbriel.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	},{
		searchterm:'Ariel',
		revRadius:1.91 * 70,
		time:0.005*4,
		radius:0.005*4 * 100,
		ecc:0.0012,
		incl:0.260,
        tilt: 0,
        stilt: 17,
		src:"res/ariel.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	}]
},{
	searchterm:'Neptune',
	revRadius:540 * 12,
	selftime:0.67,
	time:164.8,
	radius:0.3883 * 30,
	ecc:0.009,
	incl:6.43,
	tilt:28.32,
    stilt: 1.8,
	src:"res/neptunemap.jpg",
	ring:null,
    cloud:"res/grenn.jpg",
    usecloud: false,
	bump:"res/green.jpg",
	usebump:false,
	satlites:[{
		searchterm:'Triton',
		revRadius:3.55 * 50,
		time:0.008*4,
		radius:0.011*4 * 100,
		ecc:0.0,
		incl:156.885,
        tilt: 0,
        stilt: 0,
		src:"res/triton.jpg",
		ring:null,
        cloud:"res/grenn.jpg",
        usecloud: false,
		bump:"res/green.jpg",
		usebump:false
	}]
}];